version: "3.7"
services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
      - 9229:9229
    command: yarn start
    env_file:
      - .env
